vehicle {
  length_m: 4.8
  width_m: 2.0
  wheelbase_m: 2.8
  max_speed_mps: 3.0
  max_acceleration_mps2: 1.5
  max_deceleration_mps2: 2.0
  max_curvature_1pm: 0.25
  safety_margin_m: 0.35
  min_jerk_mps3: -4.0
  max_jerk_mps3: 2.0
}
planner {
  horizon_s: 8.0
  time_step_s: 0.2
  path_step_m: 0.5
  input_max_age_s: 0.5
  path_coupling_iterations: 2
  max_lane_match_distance_m: 2.0
  max_lane_heading_difference_rad: 1.0471975512
  jerk_weight: 1.0
}
